export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const CATEGORY_INIT_SUCCESS = 'CATEGORY_INIT_SUCCESS';
export const CATEGORY_CHANGE_ID = 'CATEGORY_CHANGE_ID';
export const CATEGORY_SEARCH_EMPTY = 'CATEGORY_SEARCH_EMPTY';
export const CATEGORY_ALERTED_EMPTY = 'CATEGORY_ALERTED_EMPTY';
export const CATEGORY_SEARCH_SUCCESS = 'CATEGORY_SEARCH_SUCCESS';
export const CATEGORY_RESET_PATH = 'CATEGORY_RESET_PATH';
export const CATEGORY_GET_CATEGORYNAME = 'CATEGORY_GET_CATEGORYNAME';
export const CATEGORY_RESULT_UPDATED = 'CATEGORY_RESULT_UPDATED';

export const PRODCUT_GET_SUCCESS = 'PRODCUT_GET_SUCCESS';
export const PRODCUT_SELECT_PRODUCT = 'PRODCUT_SELECT_PRODUCT';
export const PRODCUT_DETIAL_INIT = 'PRODCUT_DETIAL_INIT';